### ISSUE TITLE
When I run the npm start in ui-sortable-ng2, some errors happen!

### ISSUE THREAD

**Issue by Sunny-Kid** [angular-ui/ui-sortable#528]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-ui-sortable@2.0.0-alpha.32~prestart: angular-ui-sortable@2.0.0-alpha.32
6 silly lifecycle angular-ui-sortable@2.0.0-alpha.32~prestart: no script for prestart, continuing
7 info lifecycle angular-ui-sortable@2.0.0-alpha.32~start: angular-ui-sortable@2.0.0-alpha.32
8 verbose lifecycle angular-ui-sortable@2.0.0-alpha.32~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-ui-sortable@2.0.0-alpha.32~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/renminjie/angular2Learning/ui-sortable-ng2/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/renminjie/Library/Android/sdk/platform-tools
10 verbose lifecycle angular-ui-sortable@2.0.0-alpha.32~start: CWD: /Users/renminjie/angular2Learning/ui-sortable-ng2
11 silly lifecycle angular-ui-sortable@2.0.0-alpha.32~start: Args: [ '-c', 'gulp play' ]
12 silly lifecycle angular-ui-sortable@2.0.0-alpha.32~start: Returned: code: 1  signal: null
13 info lifecycle angular-ui-sortable@2.0.0-alpha.32~start: Failed to exec start script
14 verbose stack Error: angular-ui-sortable@2.0.0-alpha.32 start: `gulp play`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-ui-sortable@2.0.0-alpha.32
16 verbose cwd /Users/renminjie/angular2Learning/ui-sortable-ng2
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-ui-sortable@2.0.0-alpha.32 start: `gulp play`
22 error Exit status 1
23 error Failed at the angular-ui-sortable@2.0.0-alpha.32 start script 'gulp play'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-ui-sortable package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp play
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-ui-sortable
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-ui-sortable
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`
and run gulp play 
`[16:32:56] Using gulpfile ~/angular2Learning/ui-sortable-ng2/gulpfile.js
[16:32:56] Starting 'js'...
[16:32:56] Starting 'ts'...
[16:32:56] Starting 'angular2'...
[16:32:56] 'angular2' errored after 98 ms
[16:32:56] ModuleEvaluationError: $createPrivateName is not a function
    at /Users/renminjie/angular2Learning/ui-sortable-ng2/node_modules/_traceur@0.0.88@traceur/bin/traceur.js:727:18
 loaded by traceur@0.0.88/src/runtime/runtime-modules.js
[16:32:56] Finished 'js' after 121 ms
[16:32:56] Plumber found unhandled error:
 TypeError in plugin 'gulp-traceur'
Message:
    $getOwnPropertyDescriptor is not a function
Details:
    fileName: /Users/renminjie/angular2Learning/ui-sortable-ng2/src/sortable
[16:32:56] Finished 'ts' after 171 ms
`

**Comment by thgreasi** [comment]
Thanks for reporting. I will try to find some time during the coming weekends and check it out.
